### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by vickyvi17** [MORLab/sss#1]
How can I use this application to reduce a system having A B C matrices

**Comment by mariacruzvarona** [comment]
Hello!

You have to first create a "sys"-object with sss

``sys = sss(A,B,C)``

and then pass the sys-object to the reduction-function you wanna just. For instance

``q=20, sysr = tbr(sys,q)``

Have a look at the headers of the functions for more information regarding the input/output parameters as well as the options. You can also have a look at the documentation (just type "doc") or at the demos to learn how to use the toolbox.

Hope that helps!

Best,
Maria
